apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-alert-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: log-alert-operator
  template:
    metadata:
      labels:
        name: log-alert-operator
    spec:
      serviceAccountName: log-alert-operator
      containers:
        - name: log-alert-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - log-alert-operator
          imagePullPolicy: Always
          env:
            - name: demo
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "log-alert-operator"
